### ISSUE TITLE
Not loading /_next path

### ISSUE THREAD

**Issue by mattdell** [danielcondemarin/serverless-nextjs-plugin#35]
I got this integrating onto my site, but have replicated it in the example app.

Steps to reproduce

Using Serverless v1.40.0

* Clone this repo
* `$ cd examples/basic-next-serverless-app/`
* `$ yarn`
* `$ npx serverless offline`
* See lots of messages in the console such as `Serverless: GET /_next/on-demand-entries-ping (λ: notFoundErrorPage)`

<img width="682" alt="Screenshot 2019-04-03 at 12 50 25" src="https://user-images.githubusercontent.com/2536442/55476789-66c20400-560f-11e9-9746-ee0921e60438.png">

And lots of 403 status codes in the network tab for anything on the `/_next` path.

<img width="1580" alt="Screenshot 2019-04-03 at 12 53 34" src="https://user-images.githubusercontent.com/2536442/55476886-9f61dd80-560f-11e9-9c6f-25b0e5146b1b.png">

I'm not sure what to do, but this means none of my JS or CSS will load.

**Comment by mattdell** [comment]
Correction:

The above is still assuming an `assetPath` prefix. I don't want to use an S3 bucket for assets as I don't (yet) have a need for it.

So if I remove the prefix from next.config.js I get the same as above but 404 instead of 403.

**Comment by romainquellec** [comment]
Right now, this plugin doesn't embed assets except using a S3 bucket.
I think @danielcondemarin will add a feature for this with bucket offline (serverless-s3-local or something similar).

FYI, right now, on production, you NEED a bucket for files is "_next/static".

**Comment by mattdell** [comment]
Ok, fair enough if that's how it works at the moment. I'll give it a go with a bucket name.

**Comment by falconmick** [comment]
@romainquellec is there a built in way to Serverless-Offline to emulate s3? Otherwise it kinda makes it really hard to use `sls offline`

**Comment by romainquellec** [comment]
@falconmick I think so. I didnt test it myself, but try serverless-s3-local

**Comment by falconmick** [comment]
Yeah damn I thought that might be needed. Too bad there isn’t a native solution built into offline

**Comment by danielcondemarin** [comment]
Currently using serverless-offline for local development is very limited, as in, you don't get HMR or the static files uploaded to local S3 or a local server etc. This has been briefly discussed in https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/15

Ideally, when running `npx serverless-offline` alongside this plugin you have:
- Static assets hosted in some local server
- HMR working

Right now there isn't a straightforward way to do this, however is something I'll definitely look into as soon as I have some time.

**Comment by justinwhall** [comment]
If I'm following this issue correctly, `serverless offline` is not really supported when using _local_ assets in the `.next` directory? If that's the case, there's really no way to debug serverless specific issues locally?

**Comment by mattdell** [comment]
For my original issue, it's been addressed with #92 

There is no need to specify an `assetPrefix` but a bucket name is required in serverless.yml

**Comment by justinwhall** [comment]
Thanks, but that doesn't really answer my question. I see this fixes `_next` assets 404 on API gateway, but running `sls offline`, the issue persists. I'm not sure how a bucket name in the serverless.yml file would fix this?

**Comment by mattdell** [comment]
The original issue here wasn't a serverless-offline issue, though it did go off topic into that area, so that's why I've closed this one.

Looks like you have an issue opened with #93 so you'll probably have better luck there.
